# Generated by Django 3.1.7 on 2021-04-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='items')),
                ('dest', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
